# Dependencies
# markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Imaginary unit
tagline:          'Coding, Math'
description:      'Yet another blog about coding & math'
url:              https://imaginary-unit.github.io
baseurl:          /

author:
  name:           'Constantin Petrov'
  url:            https://vk.com/cat91

gems:
  [jekyll-paginate, redcarpet, jekyll-gist, pygments.rb]

paginate:         1

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/imaginary-unit/imaginary-unit.github.io
